import Image from "next/image";
import Link from "next/link";
import SectionPageNav from "../SectionPageNav";
import { guideBookProduct as product } from "./product";
import "./guide-book.css";
import "./guide-book-typography.css";

const highlights=[["01","PLAN WITH CONFIDENCE","Start an independent journey with practical context shaped by real time on the road."],["02","GO BEYOND THE OBVIOUS","Find places, roads and mountain atmosphere that make a self-led route feel personal."],["03","TRAVEL YOUR OWN WAY","Keep the freedom to choose your pace with better local knowledge."]];
const inside=[["01","PLACES","Major destinations plus lesser-known locations worth adding to your route."],["02","ROADS & ACCESS","How to get there, what to expect from the road and where additional preparation may be required."],["03","MAPS & LOCATIONS","Useful map locations and QR links designed to make planning easier from your phone."],["04","WHERE TO STAY","Yurt camps, guesthouses, camping options and practical accommodation recommendations."],["05","LOCAL KNOWLEDGE","Practical information about permits, fuel, cash, connectivity and seasonal access."],["06","EMIL RECOMMENDS","Personal routes, viewpoints, stops and places I would recommend to friends."]];
const route=["Sary-Chelek","Kara-Kamysh","Kara-Alma","Kazarman","Moldo-Ashuu","Song-Kol","Tash-Rabat","Kel-Suu","Issyk-Kul","Karakol","Jeti-Oguz","Sary-Jaz / Enylchek","Bishkek"];
const practical=[["ROAD CONDITIONS","Practical notes about mountain roads and difficult sections."],["BORDER PERMITS","Information about destinations where border-zone permits may be required."],["WHERE TO STAY","Local accommodation, yurt camps and camping information."],["LOCAL TIPS","When to arrive, what not to miss and personal recommendations."],["MAP LOCATIONS","QR codes and useful locations that can be opened from a phone."],["TRAVEL PRACTICALITIES","Fuel, cash, weather, clothing and connectivity considerations."]];
const faqs=[["WHAT FORMAT IS THE GUIDE?","A digital PDF designed to be easy to use while planning your trip and while travelling."],["IS THIS A FIXED TOUR?","No. The guide helps independent travellers plan their own journey. The current edition uses a 12-day route as its foundation, but the information can also be used when building your own itinerary."],["IS THE GUIDE UPDATED?","Yes. The guide is intended to evolve as roads, access, accommodation and destinations change."],["DO I NEED A 4X4?","Not everywhere. Some remote routes and mountain destinations may require a suitable vehicle depending on road and weather conditions."],["CAN I SEE IT BEFORE BUYING?","A free two-page preview will be available directly from this page."],["HOW WILL I RECEIVE THE GUIDE?","After payment integration is completed, the Guide Book will be delivered digitally by email after successful payment."]];
function Title({eyebrow,children,accent}:{eyebrow:string;children:React.ReactNode;accent:string}){return <div className="guide-title"><p className="eyebrow">{eyebrow}</p><h2>{children}<br/><em>{accent}</em></h2></div>}
export default function GuideBookPage(){const preview=product.previewAsset;return <main className="guide-page">
<header className="guide-header"><Link className="brand" href="/">KYRGYZSTAN<span>360</span></Link><Link href="/#explore">← ALL ADVENTURES</Link></header>
<section className="guide-hero" id="overview"><Image src="/guide-book-hiker-map.png" alt="Traveller looking at a map in the mountains of Kyrgyzstan" fill priority sizes="100vw"/><div/><div className="guide-hero-copy"><p>KYRGYZSTAN GUIDE BOOK</p><h1>Make the<br/><em>route yours.</em></h1><span>A personal guide book for travellers who want to explore Kyrgyzstan independently, with local perspective before the journey begins.</span><a href="#purchase">GET THE GUIDE ↗</a></div></section>
<SectionPageNav label="Guide book sections" items={[{href:"#why",label:"Why this guide"},{href:"#inside",label:"Inside"},{href:"#edition",label:"Edition"},{href:"#purchase",label:"Get the guide"}]}/>
<section className="guide-story" id="why"><div className="guide-photo"><Image src="/founder-kyrgyzstan.jpg" alt="Kyrgyzstan360 founder travelling in Kyrgyzstan" fill sizes="(max-width:800px) calc(100vw - 34px),42vw"/></div><div><Title eyebrow="WHY THIS GUIDE" accent="Written from here.">Not written<br/>after a trip.</Title><div className="guide-copy"><p>Many travel guides are written by travellers who spend a few weeks or months in Kyrgyzstan, collect their notes and move on.</p><p>I live here.</p><p>I travel these roads, explore new routes and return to these places throughout the year. I see when roads change, when new places open, when access becomes difficult and when destinations that were once unknown begin appearing on the tourist map.</p><p>This guide is built from local experience — and it keeps evolving with it.</p></div></div></section>
<section className="guide-route-intro"><Title eyebrow="GO WITH A PLAN" accent="Your pace.">Your route.</Title><p>Created for curious travellers who want the space to make Kyrgyzstan their own, while starting with a guide shaped by real time on the road.</p></section><section className="guide-highlights">{highlights.map(([n,t,c])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{c}</p></article>)}</section>
<section className="guide-updated"><div><Title eyebrow="BUILT TO STAY CURRENT" accent="Updated from the road.">A guide that<br/>doesn&apos;t get old.</Title><div className="guide-copy"><p>Kyrgyzstan changes quickly.</p><p>Roads improve. Mountain routes close and reopen. New guesthouses, yurt camps and experiences appear every season.</p><p>That&apos;s why this isn&apos;t a guide I wrote once and forgot about.</p><p>I keep improving it with new roads, places, practical information and discoveries from my own travels across Kyrgyzstan.</p></div></div><div className="guide-status"><span>CURRENT EDITION</span><strong>{product.updateYear}</strong><small>UPDATED REGULARLY</small></div></section>
<section className="guide-inside" id="inside"><Title eyebrow="INSIDE THE GUIDE" accent="Nothing you don&apos;t.">Everything you need.</Title><div className="guide-grid">{inside.map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section className="guide-edition" id="edition"><div><Title eyebrow="CURRENT EDITION" accent="Across Kyrgyzstan.">12 days.<br/>One big journey.</Title><div className="guide-copy"><p>The current edition follows a 12-day road journey through some of Kyrgyzstan&apos;s most spectacular landscapes.</p><p>It combines well-known destinations with remote roads, mountain passes, practical travel information and personal recommendations.</p></div></div><ol>{route.map((place,i)=><li key={place}><span>{String(i+1).padStart(2,"0")}</span>{place}</li>)}</ol></section>
<section className="guide-practical"><Title eyebrow="MORE THAN A MAP" accent="The details matter.">Know before<br/>you go.</Title><div className="guide-grid">{practical.map(([t,c])=><article key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section className="guide-preview"><div><Title eyebrow="FREE PREVIEW" accent="See before you buy.">Look inside.</Title><p>A two-page preview is being prepared with the current edition.</p>{preview?<a className="guide-button" href={preview} download>DOWNLOAD FREE PREVIEW ↓</a>:<><button className="guide-button" disabled>DOWNLOAD FREE PREVIEW ↓</button><small>PREVIEW PDF COMING SOON</small></>}</div><div className="guide-pages"><article><span>THE KYRGYZSTAN GUIDE</span><strong>12 DAYS.<br/>ONE BIG<br/>JOURNEY.</strong><i>Preview page 01</i></article><article><span>DAY 05 · SONG-KOL</span><strong>ROAD NOTES<br/>FROM THE<br/>MOUNTAINS.</strong><i>Preview page 02</i></article></div></section>
<section className="guide-purchase" id="purchase"><div><Title eyebrow="GET THE GUIDE" accent="On your own terms.">Explore Kyrgyzstan.</Title><p>One guide. Local knowledge, practical routes and the information you need to start planning your own journey through Kyrgyzstan.</p></div><div className="guide-product"><span>{product.name}</span><strong>{product.edition}</strong><b>{product.price}</b><button disabled>GET THE GUIDE — {product.price} →</button><small>DIGITAL GUIDE · PDF · INSTANT DELIVERY AFTER PAYMENT</small><em>Checkout will be available soon.</em></div></section>
<section className="guide-delivery"><div><span>01</span><strong>BUY THE GUIDE</strong></div><div><span>02</span><strong>SECURE PAYMENT</strong></div><div><span>03</span><strong>RECEIVE IT BY EMAIL</strong></div></section>
<section className="guide-faq"><Title eyebrow="QUESTIONS" accent="Good to know.">Before you go.</Title><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
</main>}