"use client";

import { KeyboardEvent, useState } from "react";
import InquiryForm from "./InquiryForm";
import "./tour-inquiry-modal.css";
import "./tour-inquiry-modal-compact.css";
import "./individual-tour-options-modal.css";
import "./individual-tour-options-compact.css";

const options = [
  { days: "05", title: "The essential route", price: "Price on request", description: "Bishkek, Song-Kul, Naryn and Issyk-Kul — a first look at Kyrgyzstan’s high lakes, mountain roads and nomadic life.", route: "Bishkek → Song-Kul → Naryn → Issyk-Kul → Karakol → Bishkek", image: "https://static.tildacdn.com/tild6433-6464-4331-a663-626566666632/DJI_0355.jpg", places: [{ name: "Song-Kul", image: "https://trevelor.com/wp-content/uploads/2024/07/Son-Kol-lake-yurt-camps.jpg" }, { name: "Skazka", image: "https://static.tildacdn.com/tild3939-3931-4866-b438-633435333933/2023-09-06_014611.jpg" }, { name: "Karakol", image: "https://triptokyrgyzstan.com/sites/default/files/media/image/19020235_waterfall0377_0.jpg" }] },
  { days: "08", title: "High lakes expedition", price: "Price on request", description: "Travel deeper through Kochkor, Song-Kul, Tash-Rabat, Kel-Suu, Naryn, Issyk-Kul and Karakol, with wide-open days on the road.", route: "Bishkek → Kochkor → Song-Kul → Tash-Rabat → Kel-Suu → Naryn → Issyk-Kul → Karakol → Bishkek", image: "/vehicles/land-cruiser-100-mountains.png", places: [{ name: "Tash-Rabat", image: "https://cdn-1.aki.kg/127/.storage/ennews/images/Culture/002ed5d80f3f9decb4ab8334446a91b2.jpg" }, { name: "Kel-Suu", image: "https://images.locationscout.net/2023/11/kel-suu-lake-kyrgyz-republic-9ahr.webp?h=1400&q=80" }, { name: "Issyk-Kul", image: "https://static.tildacdn.com/tild3939-3931-4866-b438-633435333933/2023-09-06_014611.jpg" }] },
  { days: "12", title: "The full Kyrgyzstan", price: "Price on request", description: "A slower, complete journey through high country, Silk Road landmarks, wild lakes, Issyk-Kul, Karakol and the valleys in between.", route: "Bishkek → Song-Kul → Tash-Rabat → Kel-Suu → Naryn → Issyk-Kul → Karakol → Kyrchyn → Bishkek", image: "https://asiamountains.net/assets/lib/2019/06/10/aroundlake_6.jpeg", places: [{ name: "Bishkek", image: "https://kabar.kg/media/images/IMG_5713.2e16d0ba.fill-1200x630.png" }, { name: "Song-Kul", image: "https://trevelor.com/wp-content/uploads/2024/07/Son-Kol-lake-yurt-camps.jpg" }, { name: "Kel-Suu", image: "https://static.tildacdn.one/tild6434-3662-4566-b762-386263636537/1200px-Kel-Suu_lake_.jpg" }] },
];

export default function IndividualTourOptions() {
  const [selected, setSelected] = useState<(typeof options)[number] | null>(null);
  const activate = (option: (typeof options)[number], event: KeyboardEvent<HTMLElement>) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setSelected(option); } };

  return <section className="individual-options" id="itineraries"><div className="individual-options-heading"><p>PRIVATE TOUR OPTIONS</p><h2>Choose your<br /><em>time on the road.</em></h2><span>Three ways to experience Kyrgyzstan. Hover over a route to see the places and rhythm of the journey.</span></div><div className="individual-options-grid">{options.map((option) => <article key={option.days} tabIndex={0} role="button" aria-label={`Open ${option.days}-day itinerary`} onClick={() => setSelected(option)} onKeyDown={(event) => activate(option, event)}><img className="individual-option-cover" src={option.image} alt="" loading="lazy" /><div className="individual-option-shade" /><div className="individual-option-main"><span>{option.days} DAYS</span><h3>{option.title}</h3><b>DISCOVER THE ROUTE ↗</b></div><div className="individual-option-reveal"><p>{option.description}</p><div>{option.places.map((place) => <figure key={place.name}><img src={place.image} alt={place.name} loading="lazy" /><figcaption>{place.name}</figcaption></figure>)}</div></div></article>)}</div>
    {selected && <div className="tour-modal-backdrop" role="presentation" onMouseDown={() => setSelected(null)}><section className="tour-modal individual-route-modal" role="dialog" aria-modal="true" aria-labelledby="individual-route-modal-title" onMouseDown={(event) => event.stopPropagation()}><button className="tour-modal-close" type="button" onClick={() => setSelected(null)} aria-label="Close itinerary">×</button><p className="tour-modal-kicker">INDIVIDUAL TOUR · {selected.days} DAYS</p><h2 id="individual-route-modal-title">{selected.title}</h2><p className="individual-route-description">{selected.description}</p><div className="individual-route-summary"><span>ROUTE</span><strong>{selected.route}</strong><span>PRICE</span><strong>{selected.price}</strong></div><div className="individual-route-gallery">{selected.places.map((place) => <figure key={place.name}><img src={place.image} alt={place.name} loading="lazy" /><figcaption>{place.name}</figcaption></figure>)}</div><InquiryForm compact tour={`Individual tour · ${selected.days}-day ${selected.title}`} submitLabel="BOOK THIS TOUR" /></section></div>}
  </section>;
}
