import "./hero.css";
import "./home-hero-links.css";
import InquiryForm from "./InquiryForm";

const adventures = [
  { id: "individual-tours", title: "INDIVIDUAL TOURS", description: "Your Kyrgyzstan. Your route. Your adventure.", image: "https://www.alpin-ism.com/media/page/news/_fullWidth/untitled-7167-Pano.jpg" },
  { id: "rent-service", title: "RENT & RIDE", description: "Cars, motorcycles and unforgettable mountain roads.", image: "https://www.voyagekirghizistan.com/_next/image?q=75&url=https%3A%2F%2Fnecvlggenujydiokngfg.supabase.co%2Fstorage%2Fv1%2Fobject%2Fpublic%2Fnomadays-images%2Fphotos%2F93b97591-1d9c-4fd6-a6bb-e72c4014feeb%2Fcontent%2F438e2e8f-70f6-4b60-9b40-aa2d130e1dd1%2F14d90266-d041-41e8-9c9c-5fec63d9f3e9.jpg&w=1920" },
  { title: "HIKE & CAMP", description: "Everything you need to explore the mountains.", image: "https://35photo.pro/photos_temp/sizes/1275/6375224_1500n.jpg" },
  { id: "guide-book", title: "KYRGYZSTAN GUIDEBOOK", description: "Discover the places worth going to.", image: "https://miro.medium.com/v2/resize%3Afit%3A1024/0%2AasSB7Hg6sggt1nLM.jpg" },
];

const tours = [
  { title: "5 DAYS", subtitle: "KYRGYZSTAN ADVENTURE", image: "https://d36tnp772eyphs.cloudfront.net/blogs/1/2019/02/Kyrgyzstan-mountain-landscape.jpg" },
  { title: "7 DAYS", subtitle: "THE CLASSIC JOURNEY", image: "https://images.unsplash.com/photo-1689788648186-60a2b9e1ad71?auto=format&fit=crop&w=1200&q=85" },
  { title: "9 DAYS", subtitle: "ULTIMATE KYRGYZSTAN", image: "https://triptokyrgyzstan.com/sites/default/files/images/2019-03/39739477_2214337675480162_4830902566554435584_n.jpg" },
  { title: "INDIVIDUAL 4×4", subtitle: "YOUR PRIVATE ADVENTURE", image: "https://www.alpin-ism.com/media/page/news/_fullWidth/untitled-7167-Pano.jpg" },
  { title: "FREE RIDE CAMP", subtitle: "RIDE. CAMP. REPEAT.", image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=85" },
  { title: "EXTREME TOURS", subtitle: "FOR THOSE WHO GO FURTHER", image: "https://35photo.pro/photos_temp/sizes/1275/6375224_1500n.jpg" },
];

function Arrow() { return <span aria-hidden="true">{"\u2197"}</span>; }

export default function Home() {
  return <main>
    <header className="site-header"><div className="nav-shell"><a className="brand" href="#top" aria-label="Kyrgyzstan 360 home">KYRGYZSTAN<span>360</span></a><nav aria-label="Main navigation"><a href="#explore">Explore</a><a href="#tours">Tours</a><a href="#about">About</a></nav></div></header>
    <section className="hero" id="top"><img src="/hero-kyrgyzstan.jpg" alt="Green mountain valley in Kyrgyzstan" /><div className="hero-shade" /><div className="hero-content container"><p className="eyebrow light">CENTRAL ASIA {"\u00b7"} KYRGYZSTAN</p><h1>EXPLORE<br />KYRGYZSTAN</h1><div className="hero-bottom"><p>Mountains, nomadic culture, endless roads and places you won&apos;t find anywhere else.</p><div className="hero-tour-links"><a className="button button-light" href="#explore">INDIVIDUAL JEEP TOURS <Arrow /></a><a className="button button-light" href="#winter">WINTER FREERIDE CAMPS <Arrow /></a><a className="button button-light" href="#rent-service">RENT SERVICE <Arrow /></a><a className="button button-light" href="#guide-book">KYRGYZSTAN GUIDE BOOK <Arrow /></a></div></div></div><p className="coordinates">41{String.fromCharCode(176)}12{String.fromCharCode(8242)}N {"\u00b7"} 74{String.fromCharCode(176)}46{String.fromCharCode(8242)}E</p><a className="scroll-cue" href="#explore">Scroll to explore <span>{"\u2193"}</span></a></section>
    <section className="winter-section container" id="winter" aria-labelledby="winter-title"><div className="winter-card"><img src="https://cdn1.matadornetwork.com/blogs/1/2023/03/nansen-kyrgyzstan-ski-trip.jpg" alt="Freeride skier in the snowy mountains of Kyrgyzstan" /><div className="winter-shade" /><div className="winter-copy"><p className="eyebrow light">WINTER IN THE TIEN SHAN</p><h2 id="winter-title">Explore Kyrgyzstan<br /><em>in Winter</em></h2><p className="winter-description">Deep, dry powder. Wide-open lines. Intimate freeride camps far from the crowds. Ride the Tian Shan with a private guide who knows every turn.</p><div className="winter-details"><span>Small groups · up to 3 guests</span><span>Comfortable mountain transfer</span><span>Personal freeride guide</span></div><a className="button button-light" href="/winter-freeride">BOOK A WINTER TOUR <Arrow /></a></div></div></section>
    <section className="section container" id="explore"><div className="section-heading split-heading"><div><p className="eyebrow">START HERE</p><h2>CHOOSE YOUR<br />ADVENTURE</h2></div><p className="intro">Choose how you want to experience Kyrgyzstan. We&apos;ll take care of the rest.</p></div><div className="adventure-grid">{adventures.map((item, index) => <a className={`adventure-card card-${index + 1}`} href="#contact" id={item.id} key={item.title}><img src={item.image} alt="" /><div className="image-overlay" /><div className="card-copy"><span className="card-number">0{index + 1}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><span className="circle-arrow"><Arrow /></span></div></a>)}</div></section>
    <section className="tours-section" id="tours"><div className="container"><div className="section-heading tours-heading"><div><p className="eyebrow light">FIND YOUR ROUTE</p><h2>TOURS</h2></div><p>Choose a ready-made route or let us build one around you.</p></div><div className="tour-grid">{tours.map((tour) => <a className="tour-card" href="#contact" key={tour.title}><img src={tour.image} alt="" /><div className="image-overlay" /><div className="tour-copy"><p>{tour.subtitle}</p><h3>{tour.title}</h3><span><Arrow /></span></div></a>)}</div><a className="text-link" href="#contact">PLAN MY TRIP <Arrow /></a></div></section>
    <section className="about-section container" id="about"><div className="about-stat"><span>01</span><strong>Local,<br />always.</strong></div><div className="about-copy"><p className="eyebrow">WHY KYRGYZSTAN360</p><h2>Travel with people who call these mountains home.</h2><p>We pair local knowledge with thoughtful planning, leaving enough room for the unexpected moments that make a journey unforgettable.</p><a className="text-link dark" href="#contact">PLAN MY TRIP <Arrow /></a></div><div className="about-stat"><span>02</span><strong>Wild by<br />nature.</strong></div></section>
    <section className="contact-section" id="contact"><div className="container contact-inner"><p className="eyebrow">START YOUR JOURNEY</p><h2>Leave an inquiry<br /><em>and we&apos;ll contact you.</em></h2><p>Just leave your details and we&apos;ll get back to you shortly.</p><InquiryForm /></div></section>
    <footer><div className="container footer-inner"><a className="brand" href="#top">KYRGYZSTAN<span>360</span></a><p>Adventure begins where the road ends.</p><a href="mailto:tataremil2@gmail.com">tataremil2@gmail.com</a><a href="#contact">PLAN MY TRIP</a></div></footer>
  </main>;
}
