import Image from "next/image";
import "./hero.css";
import "./home-hero-links.css";
import "./home-sticky-nav.css";
import "./home-reviews.css";
import "./home-contact.css";
import "./home-founder.css";
import InquiryForm from "./InquiryForm";
import ReviewForm from "./ReviewForm";
import WinterPromoModal from "./WinterPromoModal";

const adventures = [
  { number: "01", title: "INDIVIDUAL TOUR", description: "From 1 guest. A private route, built around you.", href: "/tours/individual", image: "/individual-tour.jpg" },
  { number: "02", title: "GROUP TOUR", description: "From 3 guests. Share the road and the stories.", href: "/tours/group", image: "/group-tour.jpg" },
  { number: "03", title: "RENT SERVICE", description: "Prepared 4×4 vehicles, motorcycles and hiking gear for journeys made on your own terms.", href: "/rent", id: "rent", image: "/rent-service-camp.jpg" },
  { number: "04", title: "KYRGYZSTAN GUIDE BOOK", description: "Explore Kyrgyzstan on your own using my carefully prepared guide book.", href: "/guide-book", image: "/guide-book-hiker-map.png" },
];

// Demo-only data. Replace with verified customer reviews before publishing testimonials.
const placeholderReviews = [
  { label: "DEMO GUEST 01", rating: 5, text: "Placeholder review text. Replace with a verified guest review." },
  { label: "DEMO GUEST 02", rating: 4, text: "Placeholder review text. Replace with a verified guest review." },
];

const demoAverageRating = placeholderReviews.reduce((total, review) => total + review.rating, 0) / placeholderReviews.length;

function Arrow() { return <span aria-hidden="true">{"\u2197"}</span>; }

function TourIcon({ kind }: { kind: "jeep" | "freeride" | "rent" | "guide" }) {
  if (kind === "jeep") return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M3 16v-5l2-4h10l3 4h3v5M5 16h14M7 16a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm14 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0ZM7 11h7" /></svg>;
  if (kind === "freeride") return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><circle cx="13.5" cy="4.5" r="1.5" /><path d="m12.5 7-2.5 5 4 3m-3-5 5 1m-2 4 3 3M4 19h16" /></svg>;
  if (kind === "rent") return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="m3 19 7-12 7 12M10 7l7 12M3 19h18M10 19v-4l2-2 2 2v4" /></svg>;
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M4 5.5A3.5 3.5 0 0 1 8 5c2 0 3 .8 4 2 1-1.2 2-2 4-2a3.5 3.5 0 0 1 4 3.5V19a4 4 0 0 0-4-2c-2 0-3 .8-4 2-1-1.2-2-2-4-2a4 4 0 0 0-4 2V5.5ZM12 7v12" /></svg>;
}

export default function Home() {
  return <main>
    <header className="site-header"><div className="nav-shell"><a className="brand" href="#top" aria-label="Kyrgyzstan 360 home">KYRGYZSTAN<span>360</span></a><nav aria-label="Main navigation"><a className="winter-nav-link" href="#winter">Winter</a><a href="#explore">Jeep tour</a><a href="#rent">Rent service</a><a href="#reviews">Reviews</a><a href="#contact">Contact</a></nav></div></header>
    <section className="hero" id="top"><img src="/hero-kyrgyzstan.jpg" alt="Green mountain valley in Kyrgyzstan" /><div className="hero-shade" /><div className="hero-content container"><p className="eyebrow light">CENTRAL ASIA {"\u00b7"} KYRGYZSTAN</p><h1>EXPLORE<br />KYRGYZSTAN</h1><div className="hero-bottom"><p>Mountains, nomadic culture, endless roads and places you won&apos;t find anywhere else.</p><div className="hero-tour-links"><a className="button button-light" href="#explore"><TourIcon kind="jeep" />INDIVIDUAL JEEP TOURS</a><a className="button button-light winter-season-cta" href="#winter"><TourIcon kind="freeride" />WINTER SEASON</a><a className="button button-light" href="/rent"><TourIcon kind="rent" />RENT SERVICE</a><a className="button button-light" href="/guide-book"><TourIcon kind="guide" />KYRGYZSTAN GUIDE BOOK</a></div></div></div><p className="coordinates">41{String.fromCharCode(176)}12{String.fromCharCode(8242)}N {"\u00b7"} 74{String.fromCharCode(176)}46{String.fromCharCode(8242)}E</p><a className="scroll-cue" href="#explore">Scroll to explore <span>{"\u2193"}</span></a></section>
    <section className="winter-section container" id="winter" aria-labelledby="winter-title"><div className="winter-card"><a className="winter-image-link" href="/winter-freeride" aria-label="Explore the Winter Freeride tour"><img src="https://cdn1.matadornetwork.com/blogs/1/2023/03/nansen-kyrgyzstan-ski-trip.jpg" alt="Freeride skier in the snowy mountains of Kyrgyzstan" /></a><div className="winter-shade" /><div className="winter-copy"><p className="eyebrow light">WINTER IN THE TIEN SHAN</p><h2 id="winter-title">Explore Kyrgyzstan<br /><em>in Winter</em></h2><p className="winter-description">Deep, dry powder. Wide-open lines. Intimate freeride camps far from the crowds. Ride the Tian Shan with a private guide who knows every turn.</p><div className="winter-event-row"><a className="winter-fwt" href="/winter-freeride#calendar"><span className="winter-fwt-mark" aria-hidden="true"><svg viewBox="0 0 42 42"><path d="M5 31 15 15l5 8 6-12 11 20" /><path d="m13 31 8-9 5 6 4-5 7 8" /></svg></span><div><strong>FREERIDE WORLD TOUR QUALIFIER</strong><p>Official qualifier event in the mountains of Kyrgyzstan.</p></div></a><a className="winter-fwt" href="/winter-freeride#calendar"><span className="winter-fwt-mark" aria-hidden="true"><svg viewBox="0 0 42 42"><path d="M6 30h30M10 30l8-15 5 9 4-6 9 12" /><path d="M12 35h18" /></svg></span><div><strong>SILK ROAD FREERIDE</strong><p>We arrange transfers to the competition on January 14–17, 2027.</p></div></a></div><a className="button button-light" href="/winter-freeride">EXPLORE <Arrow /></a></div></div></section>
    <section className="section container" id="explore"><div className="section-heading split-heading"><div><p className="eyebrow">START HERE</p><h2>CHOOSE YOUR<br />ADVENTURE</h2></div><p className="intro">Choose how you want to experience Kyrgyzstan. We&apos;ll take care of the rest.</p></div><div className="adventure-grid">{adventures.map((item) => <a className={`adventure-card card-${item.number}`} href={item.href} id={item.id} key={item.title}><img src={item.image} alt="" /><div className="image-overlay" /><div className="card-copy"><span className="card-number">{item.number}</span><div><h3>{item.title}</h3><p>{item.description}</p></div><span className="circle-arrow"><Arrow /></span></div></a>)}</div></section>
    <section className="founder-section" aria-labelledby="founder-title"><div className="container founder-inner"><div className="founder-photo"><Image src="/founder-kyrgyzstan.jpg" alt="Kyrgyzstan360 founder by a yurt and lake in Kyrgyzstan" fill sizes="(max-width: 700px) calc(100vw - 34px), 45vw" /></div><div className="founder-story"><p className="eyebrow">WHY KYRGYZSTAN360</p><h2 id="founder-title">Travel with<br />a local.<br /><em>Discover Kyrgyzstan with me.</em></h2><div className="founder-copy"><p>Kyrgyzstan is more than a destination to me. These mountains are where I spend my life — driving remote roads, hiking, skiing, guiding and constantly discovering new places.</p><p>Over the years, I’ve built a community around me of guides, freeriders, athletes, travellers and friends who are actively developing outdoor culture in Kyrgyzstan — from pushing freeride forward to taking part in some of the country’s major events.</p><p>That means your journey isn’t limited to a standard itinerary. You travel through a network of local people, places and experiences that I genuinely know and trust.</p><p>But the most important thing is simple: I love what I do.</p><p>I love the mountains. I love the road. And I want to share that feeling with people who have the same curiosity and spirit of adventure.</p><p>I’m not inviting you to simply visit Kyrgyzstan.</p><p>I’m inviting you to discover it with me.</p></div><div className="founder-values"><span>MOUNTAINS ARE MY HOME</span><span>LOCAL COMMUNITY</span><span>PERSONAL JOURNEYS</span></div><a className="founder-instagram" href="https://www.instagram.com/zakirov_emil_trvl/" target="_blank" rel="noreferrer">MY INSTAGRAM ↗</a></div></div></section>
    <section className="reviews-section" id="reviews"><div className="container reviews-inner"><div className="reviews-showcase"><div className="reviews-showcase-heading"><p className="eyebrow">YOUR REVIEWS</p><h2 className="reviews-heading">Stories from<br /><em>the road.</em></h2><p>Demo content for the layout — replace with verified guest reviews before publishing.</p><small className="review-average">DEMO AVERAGE · {demoAverageRating.toFixed(1)} / 5</small></div><div className="reviews-grid">{placeholderReviews.map((review) => <article className="guest-review" key={review.label}><div className="guest-review-stars" aria-label={`${review.rating} out of 5 stars`}>{[1, 2, 3, 4, 5].map((star) => <span className={star <= review.rating ? "is-filled" : ""} key={star}>★</span>)}</div><p>{review.text}</p><strong>{review.label}</strong></article>)}</div></div><div className="reviews-bridge" aria-hidden="true" /><div className="leave-review"><p className="eyebrow">SHARE YOUR EXPERIENCE</p><h2 className="reviews-heading">Leave a<br /><em>review.</em></h2><span>Tell future travellers about your time in Kyrgyzstan. It takes a minute and does not require an account.</span><ReviewForm /></div><div className="external-review-links"><span>Or leave a review on</span><a href="https://www.google.com/maps/search/?api=1&query=Kyrgyzstan360%20Tourism%20In%20Kyrgyzstan" target="_blank" rel="noreferrer">Google Maps ↗</a><a href="https://www.tripadvisor.com/Attraction_Review-g815340-d32874967-Reviews-Kyrgyzstan360_Tourism_In_Kyrgyzstan-Karakol_Issyk_Kul_Province.html" target="_blank" rel="noreferrer">Tripadvisor ↗</a></div></div></section>
    <section className="contact-section" id="contact"><div className="container contact-inner"><p className="eyebrow">START YOUR JOURNEY</p><h2>Leave an inquiry<br /><em>and we&apos;ll contact you.</em></h2><p>Just leave your details and we&apos;ll get back to you shortly.</p><InquiryForm /></div></section>
    <footer><div className="container footer-inner"><a className="brand" href="#top">KYRGYZSTAN<span>360</span></a><p>Adventure begins where the road ends.</p><nav className="footer-legal" aria-label="Legal"><span>LEGAL</span><a href="/legal">Legal Information</a><a href="/terms">Terms &amp; Conditions</a><a href="/privacy">Privacy Policy</a><a href="/cookies">Cookie Policy</a></nav><a href="mailto:tataremil2@gmail.com">tataremil2@gmail.com</a><a href="#contact">PLAN MY TRIP</a></div></footer>
  <WinterPromoModal />
  </main>;
}




